name: couchclient
version: 0.3.0+3
description: >
  A Couchbase client library written in Dart language.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  memcached_client: any
  crypto: any
  unittest: any
  logging: any
