name: couchclient
version: 0.2.0
description: >
  A Couchbase client library written in Dart language.
authors:
- Henri Chen <henrichen@rikulo.org>
homepage: http://rikulo.org
dependencies:
  memcached_client:
  unittest:
  logging:
